import { PizzaSize } from '../types/pizza-size';
import { PizzaIngredientType } from '../types/pizza-ingredient.enum';

export const popularPizzas = [
  {
    name: 'Margherita',
    description: 'Classic pizza with tomato, mozzarella, and basil',
    price: 8.99,
    ingredients: [
      { type: PizzaIngredientType.TOMATO, amount: 80 },
      { type: PizzaIngredientType.MOZZARELLA, amount: 100 },
      { type: PizzaIngredientType.BASIL, amount: 5 },
    ],
    isAvailable: true,
    size: PizzaSize.MEDIUM,
    calories: 900,
    imageUrl: '/pizza1.jpg',
  },
  {
    name: 'Pepperoni',
    description: 'Pepperoni, mozzarella, and tomato',
    price: 10.99,
    ingredients: [
      { type: PizzaIngredientType.TOMATO, amount: 80 },
      { type: PizzaIngredientType.MOZZARELLA, amount: 100 },
      { type: PizzaIngredientType.PEPPERONI, amount: 60 },
    ],
    isAvailable: true,
    size: PizzaSize.MEDIUM,
    calories: 1100,
    imageUrl: '/pizza2.jpg',
  },
  {
    name: 'Quattro Formaggi',
    description: 'Mozzarella, blue cheese, parmesan, and cheese',
    price: 11.99,
    ingredients: [
      { type: PizzaIngredientType.MOZZARELLA, amount: 60 },
      { type: PizzaIngredientType.BLUE_CHEESE, amount: 40 },
      { type: PizzaIngredientType.PARMESAN, amount: 30 },
      { type: PizzaIngredientType.CHEESE, amount: 40 },
    ],
    isAvailable: true,
    size: PizzaSize.MEDIUM,
    calories: 1200,
    imageUrl: '/pizza3.jpg',
  },
  {
    name: 'Hawaiian',
    description: 'Ham, pineapple, mozzarella, and tomato',
    price: 10.49,
    ingredients: [
      { type: PizzaIngredientType.TOMATO, amount: 80 },
      { type: PizzaIngredientType.MOZZARELLA, amount: 100 },
      { type: PizzaIngredientType.HAM, amount: 50 },
      { type: PizzaIngredientType.PINEAPPLE, amount: 50 },
    ],
    isAvailable: true,
    size: PizzaSize.MEDIUM,
    calories: 1050,
    imageUrl: '/pizza4.jpg',
  },
  {
    name: 'Vegetarian',
    description: 'Peppers, onion, mushroom, olives, and mozzarella',
    price: 9.99,
    ingredients: [
      { type: PizzaIngredientType.PEPPERS, amount: 40 },
      { type: PizzaIngredientType.ONION, amount: 30 },
      { type: PizzaIngredientType.MUSHROOM, amount: 40 },
      { type: PizzaIngredientType.OLIVES, amount: 20 },
      { type: PizzaIngredientType.MOZZARELLA, amount: 80 },
    ],
    isAvailable: true,
    size: PizzaSize.MEDIUM,
    calories: 950,
    imageUrl: '/pizza5.jpg',
  },
  {
    name: 'BBQ Chicken',
    description: 'Chicken, BBQ sauce, onion, and mozzarella',
    price: 12.49,
    ingredients: [
      { type: PizzaIngredientType.CHICKEN, amount: 70 },
      { type: PizzaIngredientType.BBQ_SAUCE, amount: 50 },
      { type: PizzaIngredientType.ONION, amount: 30 },
      { type: PizzaIngredientType.MOZZARELLA, amount: 80 },
    ],
    isAvailable: true,
    size: PizzaSize.MEDIUM,
    calories: 1150,
    imageUrl: '/pizza6.jpg',
  },
  {
    name: 'Diavola',
    description: 'Spicy salami, tomato, mozzarella, and peppers',
    price: 11.49,
    ingredients: [
      { type: PizzaIngredientType.SALAMI, amount: 60 },
      { type: PizzaIngredientType.TOMATO, amount: 80 },
      { type: PizzaIngredientType.MOZZARELLA, amount: 80 },
      { type: PizzaIngredientType.PEPPERS, amount: 30 },
    ],
    isAvailable: true,
    size: PizzaSize.MEDIUM,
    calories: 1120,
    imageUrl: '/pizza7.jpg',
  },
  {
    name: 'Capricciosa',
    description: 'Ham, mushrooms, artichoke, olives, and tomato',
    price: 11.99,
    ingredients: [
      { type: PizzaIngredientType.HAM, amount: 50 },
      { type: PizzaIngredientType.MUSHROOM, amount: 40 },
      { type: PizzaIngredientType.ARTICHOKE, amount: 30 },
      { type: PizzaIngredientType.OLIVES, amount: 20 },
      { type: PizzaIngredientType.TOMATO, amount: 80 },
    ],
    isAvailable: true,
    size: PizzaSize.MEDIUM,
    calories: 1080,
    imageUrl: '/pizza8.jpg',
  },
  {
    name: 'Prosciutto e Funghi',
    description: 'Ham, mushrooms, mozzarella, and tomato',
    price: 11.49,
    ingredients: [
      { type: PizzaIngredientType.HAM, amount: 50 },
      { type: PizzaIngredientType.MUSHROOM, amount: 40 },
      { type: PizzaIngredientType.MOZZARELLA, amount: 80 },
      { type: PizzaIngredientType.TOMATO, amount: 80 },
    ],
    isAvailable: true,
    size: PizzaSize.MEDIUM,
    calories: 1070,
    imageUrl: '/pizza9.jpg',
  },
  {
    name: 'Quattro Stagioni',
    description:
      'Ham, mushrooms, artichoke, olives, and tomato, divided in quarters',
    price: 12.49,
    ingredients: [
      { type: PizzaIngredientType.HAM, amount: 40 },
      { type: PizzaIngredientType.MUSHROOM, amount: 30 },
      { type: PizzaIngredientType.ARTICHOKE, amount: 20 },
      { type: PizzaIngredientType.OLIVES, amount: 15 },
      { type: PizzaIngredientType.TOMATO, amount: 70 },
    ],
    isAvailable: true,
    size: PizzaSize.MEDIUM,
    calories: 1100,
    imageUrl: '/pizza10.jpg',
  },
  {
    name: 'Bufalina',
    description: 'Buffalo mozzarella, tomato, and basil',
    price: 12.99,
    ingredients: [
      { type: PizzaIngredientType.MOZZARELLA, amount: 100 },
      { type: PizzaIngredientType.TOMATO, amount: 80 },
      { type: PizzaIngredientType.BASIL, amount: 5 },
    ],
    isAvailable: true,
    size: PizzaSize.MEDIUM,
    calories: 950,
    imageUrl: '/pizza11.jpg',
  },
  {
    name: 'Tonno e Cipolla',
    description: 'Tuna, onion, mozzarella, and tomato',
    price: 11.99,
    ingredients: [
      { type: PizzaIngredientType.TUNA, amount: 60 },
      { type: PizzaIngredientType.ONION, amount: 30 },
      { type: PizzaIngredientType.MOZZARELLA, amount: 80 },
      { type: PizzaIngredientType.TOMATO, amount: 80 },
    ],
    isAvailable: true,
    size: PizzaSize.MEDIUM,
    calories: 1050,
    imageUrl: '/pizza12.jpg',
  },
  {
    name: 'Frutti di Mare',
    description: 'Seafood mix, garlic, tomato, and parsley',
    price: 13.99,
    ingredients: [
      { type: PizzaIngredientType.TUNA, amount: 30 },
      { type: PizzaIngredientType.ANCHOVY, amount: 20 },
      { type: PizzaIngredientType.GARLIC, amount: 10 },
      { type: PizzaIngredientType.TOMATO, amount: 80 },
    ],
    isAvailable: true,
    size: PizzaSize.MEDIUM,
    calories: 1150,
    imageUrl: '/pizza13.jpg',
  },
  {
    name: 'Boscaiola',
    description: 'Sausage, mushrooms, mozzarella, and tomato',
    price: 12.49,
    ingredients: [
      { type: PizzaIngredientType.SAUSAGE, amount: 60 },
      { type: PizzaIngredientType.MUSHROOM, amount: 40 },
      { type: PizzaIngredientType.MOZZARELLA, amount: 80 },
      { type: PizzaIngredientType.TOMATO, amount: 80 },
    ],
    isAvailable: true,
    size: PizzaSize.MEDIUM,
    calories: 1120,
    imageUrl: '/pizza14.jpg',
  },
  {
    name: 'Carbonara',
    description: 'Bacon, egg, parmesan, and mozzarella',
    price: 12.99,
    ingredients: [
      { type: PizzaIngredientType.BACON, amount: 50 },
      { type: PizzaIngredientType.EGG, amount: 1 },
      { type: PizzaIngredientType.PARMESAN, amount: 30 },
      { type: PizzaIngredientType.MOZZARELLA, amount: 80 },
    ],
    isAvailable: true,
    size: PizzaSize.MEDIUM,
    calories: 1200,
    imageUrl: '/pizza15.jpg',
  },
  {
    name: 'Siciliana',
    description: 'Anchovy, olives, capers, tomato, and oregano',
    price: 11.99,
    ingredients: [
      { type: PizzaIngredientType.ANCHOVY, amount: 20 },
      { type: PizzaIngredientType.OLIVES, amount: 20 },
      { type: PizzaIngredientType.TOMATO, amount: 80 },
      { type: PizzaIngredientType.OREGANO, amount: 5 },
    ],
    isAvailable: true,
    size: PizzaSize.MEDIUM,
    calories: 1050,
    imageUrl: '/pizza16.jpg',
  },
  {
    name: 'Romana',
    description: 'Anchovy, capers, mozzarella, and tomato',
    price: 11.49,
    ingredients: [
      { type: PizzaIngredientType.ANCHOVY, amount: 20 },
      { type: PizzaIngredientType.CHEESE, amount: 40 },
      { type: PizzaIngredientType.MOZZARELLA, amount: 80 },
      { type: PizzaIngredientType.TOMATO, amount: 80 },
    ],
    isAvailable: true,
    size: PizzaSize.MEDIUM,
    calories: 1050,
    imageUrl: '/pizza17.jpg',
  },
  {
    name: 'Bufala e Crudo',
    description: 'Buffalo mozzarella, prosciutto, and tomato',
    price: 13.49,
    ingredients: [
      { type: PizzaIngredientType.MOZZARELLA, amount: 100 },
      { type: PizzaIngredientType.PROSCIUTTO, amount: 50 },
      { type: PizzaIngredientType.TOMATO, amount: 80 },
    ],
    isAvailable: true,
    size: PizzaSize.MEDIUM,
    calories: 1100,
    imageUrl: '/pizza18.jpg',
  },
  {
    name: 'Zucchini e Ricotta',
    description: 'Zucchini, ricotta, mozzarella, and tomato',
    price: 11.99,
    ingredients: [
      { type: PizzaIngredientType.ZUCCHINI, amount: 40 },
      { type: PizzaIngredientType.RICOTTA, amount: 50 },
      { type: PizzaIngredientType.MOZZARELLA, amount: 80 },
      { type: PizzaIngredientType.TOMATO, amount: 80 },
    ],
    isAvailable: true,
    size: PizzaSize.MEDIUM,
    calories: 1000,
    imageUrl: '/pizza19.jpg',
  },
  {
    name: 'Spinaci e Gorgonzola',
    description: 'Spinach, blue cheese, mozzarella, and tomato',
    price: 12.49,
    ingredients: [
      { type: PizzaIngredientType.SPINACH, amount: 40 },
      { type: PizzaIngredientType.BLUE_CHEESE, amount: 40 },
      { type: PizzaIngredientType.MOZZARELLA, amount: 80 },
      { type: PizzaIngredientType.TOMATO, amount: 80 },
    ],
    isAvailable: true,
    size: PizzaSize.MEDIUM,
    calories: 1050,
    imageUrl: '/pizza20.jpg',
  },
  {
    name: 'Broccoli e Salsiccia',
    description: 'Broccoli, sausage, mozzarella, and tomato',
    price: 12.49,
    ingredients: [
      { type: PizzaIngredientType.BROCCOLI, amount: 40 },
      { type: PizzaIngredientType.SAUSAGE, amount: 60 },
      { type: PizzaIngredientType.MOZZARELLA, amount: 80 },
      { type: PizzaIngredientType.TOMATO, amount: 80 },
    ],
    isAvailable: true,
    size: PizzaSize.MEDIUM,
    calories: 1100,
    imageUrl: '/pizza21.jpg',
  },
];
